### ISSUE TITLE
You no need to display cancel button on iPad

### ISSUE THREAD

**Issue by k06a** [steipete/PSAlertView#11]
I see cancel button but can't see last of added buttons...

iOS 7

**Comment by steipete** [comment]
Please open an issue with steps to reproduce, or don't report at all.

**Comment by javsmo** [comment]
Same problem here. Only on iPad.

The code is the following:

``` Objective-C
PSPDFActionSheet * myAction = [[PSPDFActionSheet alloc] initWithTitle:@"Font size"];
[myAction setCancelButtonWithTitle:@"Cancel" block:^{
}];
[myAction addButtonWithTitle:@"Small" block:^{
    [ConfigurationManager shared].fontSize = ConfFontSmall;
    _fontSizeLabel.text = @"Small";
    [[ConfigurationManager shared] save];
}];
[myAction addButtonWithTitle:@"Medium" block:^{
    [ConfigurationManager shared].fontSize = ConfFontMedium;
    _fontSizeLabel.text = @"Medium";
    [[ConfigurationManager shared] save];
}];
[myAction addButtonWithTitle:@"Large" block:^{
    [ConfigurationManager shared].fontSize = ConfFontLarge;
    _fontSizeLabel.text = @"Large";
    [[ConfigurationManager shared] save];
}];
[myAction showInView:self.view.window];
```

The result is the following:
![error](https://cloud.githubusercontent.com/assets/1733085/2895223/492b6126-d55d-11e3-855d-0f05f76a9249.png)

Without the cancel button, the result is this:
![error2](https://cloud.githubusercontent.com/assets/1733085/2895268/c9d1da12-d55d-11e3-8aa6-03ee0d4b5e95.png)

Also only the first button has top and bottom borders.
