### ISSUE TITLE
Wrong block called for button.

### ISSUE THREAD

**Issue by pwightman** [steipete/PSAlertView#5]
I'm using the `0.0.1` CocoaPods version, which is where this (it seems) bug manifested itself.

With the following code:

``` objective-c
[alertView addButtonWithTitle:@"Cancel"];

[alertView addButtonWithTitle:@"Connect" block:^{
    NSString *host = [alertView textFieldAtIndex:0].text;
    [_networkManager connectWithIp:host];
}];
```

Tapping the "Cancel" button calls the block I passed in to "Connect", and tapping "Connect" does nothing. This may be fixed in the `1.0.0` version, but it doesn't appear to be in the CocoaPods repo. I can look into it more to find the source when it's not Christmas Day, but just wanted to get a bug report written when I have a minute here :-)

Thanks for the great library! There's lots of AlertView/ActionSheet wrappers out there (including ones I wrote myself!) and your API is by far my favorite.

**Comment by steipete** [comment]
Thanks for the kind words :)

I've subclassed the regular addButtonWithTitle call so that an empty block will be added there as well, this should fix your problems (or simply use setCancelButtonWithTitle:block:)
