### ISSUE TITLE
Resolve missing UIColor+PSDFKitAdditions import

### ISSUE THREAD

**Issue by egrim** [steipete/PSAlertView#6]
Recent updates add an import statement for a file not included in this repo:

``` objective-c
#import "UIColor+PSPDFKitAdditions.h"
```

Please add the missing file or otherwise remove the dependency.

Thanks!

**Comment by egrim** [comment]
Dependency added by c259b31873fc0e7e63d5874fda5bee85acb69d79

This fix is also of interest to @tonyarnold

**Comment by steipete** [comment]
Done.
