### ISSUE TITLE
Delegate method is never called

### ISSUE THREAD

**Issue by tonyarnold** [steipete/PSAlertView#8]
Hi Pieter, I'm having trouble getting `- (BOOL)alertViewShouldEnableFirstOtherButton:(UIAlertView *)alertView` to fire when using PSPDFAlertView. I set the delegate after creating the instance, but before I show or add any buttons. 

Is this working for you?

**Comment by steipete** [comment]
Never tried that - it's properly forwarded though. Weird.

**Comment by tonyarnold** [comment]
So it turns out that unless you provide a value for the `otherButtonTitles, …` parameter at UIAlertView initialisation, this delegate method is never called. UIAlertView Y U BUGGY? :trollface:

**Comment by tonyarnold** [comment]
I've also filed a radar: http://openradar.appspot.com/radar?id=6189750637559808
